AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aws_x_ray_sam

  Sample SAM Template for aws_x_ray_sam


Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: hello_world/
      Handler: app.lambda_handler
      Tracing: Active
      Environment:
        Variables:
          POWERTOOLS_SERVICE_NAME: hello_world
      Layers:
        - !Sub arn:aws:lambda:us-east-1:017000801446:layer:AWSLambdaPowertoolsPythonV2:69
      Runtime: python3.11
      Architectures:
        - x86_64

Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
